delimiter /


DROP TABLE USER_APP CASCADE CONSTRAINTS
/
DROP TABLE geograficalpoints CASCADE CONSTRAINTS
/
DROP TABLE PARKS CASCADE CONSTRAINTS
/
DROP TABLE BICYCLES CASCADE CONSTRAINTS
/
DROP TABLE ESCOOTERS CASCADE CONSTRAINTS
/
DROP VIEW VEHICLES
/
DROP TABLE POIS CASCADE CONSTRAINTS
/
DROP TABLE Trips CASCADE CONSTRAINTS
/
DROP TABLE Invoice_Line CASCADE CONSTRAINTS
/
DROP TABLE paths CASCADE CONSTRAINTS
/